### ISSUE TITLE
Document Need to Install Python in README File

### ISSUE THREAD

**Issue by gkapfham** [CommittedTeam/CommitCanvas#16]
- [X] I have searched the [issues](https://github.com/CommittedTeam/CommitCanvas/issues) of this repo and believe that this is not a duplicate.
- [X] I have read the [README.md](https://github.com/CommittedTeam/CommitCanvas) and believe that my question is not covered.

## Issue

The current version of the Installation section does not explain that
CommitCanvas uses Python to perform the operations of the pre-commit hook. As
such, the README file should be enhanced by first explaining the dependency on
Python. Second, the README should provide basic instructions on how to install
Python, providing references to external documentation when appropriate. While I
acknowledge that the existing documentation does include this:

```
minimum_pre_commit_version: 1.21.0
repos:

# check with commitcanvas.
- repo: https://github.com/CommittedTeam/CommitCanvas
  rev: the revision or tag to clone at
  hooks:
    - id: commitcanvas
      language_version: python3.7
      language: python
      stages: [prepare-commit-msg]

```

and that does mention `python3.7` I think that this dependency needs to be made
more explicit.
